import { readFile, readdir, writeFile } from "node:fs/promises";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const here = dirname(fileURLToPath(import.meta.url));
const PACKS_DIR = resolve(here, "../../../industry-packs");
const OUT_FILE = resolve(here, "../src/pack/packs.generated.ts");

const files = (await readdir(PACKS_DIR)).filter((f) => f.endsWith(".yaml"));
files.sort();

const entries = [];
for (const file of files) {
  const name = file.replace(".yaml", "");
  const raw = await readFile(join(PACKS_DIR, file), "utf-8");
  const data = yaml.load(raw);
  entries.push([name, data]);
}

const body = entries
  .map(([name, data]) => `  ${JSON.stringify(name)}: ${JSON.stringify(data, null, 2)},`)
  .join("\n");

const out = `// Generated by scripts/generate-packs.mjs — do not edit by hand.
// Re-run: npm run generate-packs --workspace=@metier/core
import type { IndustryPack } from "../types.js";

export const PACKS: Record<string, IndustryPack> = {
${body}
};
`;

await writeFile(OUT_FILE, out, "utf-8");
console.log(`Wrote ${entries.length} packs to ${OUT_FILE}`);
