// Generated by scripts/generate-packs.mjs — do not edit by hand.
// Re-run: npm run generate-packs --workspace=@metier/core
import type { IndustryPack } from "../types.js";

export const PACKS: Record<string, IndustryPack> = {
  "data": {
  "name": "Data & Analytics",
  "aliases": [
    "data",
    "data science",
    "data analytics",
    "business intelligence",
    "BI",
    "data engineering",
    "machine learning",
    "数据",
    "データ",
    "Daten",
    "données"
  ],
  "keywords": {
    "hard_skills": [
      "data analysis",
      "statistical modeling",
      "machine learning",
      "data pipeline",
      "ETL",
      "data visualization",
      "A/B testing",
      "predictive modeling",
      "natural language processing",
      "deep learning",
      "feature engineering",
      "data governance",
      "data warehousing",
      "experiment design"
    ],
    "soft_skills": [
      "analytical thinking",
      "storytelling with data",
      "cross-functional collaboration",
      "problem solving",
      "business acumen",
      "communication"
    ],
    "certifications": [
      "Google Data Analytics Certificate",
      "AWS Data Analytics Specialty",
      "Databricks Certified",
      "Tableau Desktop Specialist",
      "Microsoft Azure Data Scientist",
      "dbt Analytics Engineering"
    ],
    "tools": [
      "Python",
      "SQL",
      "R",
      "Tableau",
      "Power BI",
      "Snowflake",
      "Databricks",
      "Apache Spark",
      "dbt",
      "Looker",
      "Jupyter",
      "Airflow"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Technical Depth",
      "weight": 0.25
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.2
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Certification Alignment",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Soft Skills",
      "weight": 0.1
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    },
    {
      "name": "Growth Potential",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "DataJobs",
      "url": "https://datajobs.com"
    },
    {
      "name": "Kaggle Jobs",
      "url": "https://www.kaggle.com/jobs"
    }
  ],
  "interview_questions": {
    "technical": [
      "Explain the difference between L1 and L2 regularization",
      "How would you design a recommendation system?",
      "Walk me through your approach to cleaning a messy dataset",
      "How do you validate a machine learning model?"
    ],
    "behavioral": [
      "Tell me about a time your analysis changed a business decision",
      "How do you communicate complex findings to non-technical stakeholders?",
      "Describe a project where you had to work with incomplete data"
    ],
    "case": [
      "Customer churn has increased 20%. How would you approach this analytically?"
    ]
  },
  "resume_style": "modern"
},
  "design": {
  "name": "Design & UX",
  "aliases": [
    "design",
    "UX",
    "UI",
    "product design",
    "graphic design",
    "visual design",
    "UX research",
    "设计",
    "デザイン",
    "Design",
    "conception"
  ],
  "keywords": {
    "hard_skills": [
      "user research",
      "wireframing",
      "prototyping",
      "interaction design",
      "visual design",
      "design systems",
      "usability testing",
      "information architecture",
      "responsive design",
      "accessibility (WCAG)",
      "typography",
      "motion design",
      "design thinking",
      "user journey mapping"
    ],
    "soft_skills": [
      "empathy",
      "storytelling",
      "cross-functional collaboration",
      "iterative thinking",
      "presentation skills",
      "feedback incorporation"
    ],
    "certifications": [
      "Google UX Design Certificate",
      "Nielsen Norman UX Certification",
      "Interaction Design Foundation"
    ],
    "tools": [
      "Figma",
      "Sketch",
      "Adobe Creative Suite",
      "InVision",
      "Framer",
      "Miro",
      "Maze",
      "Hotjar",
      "Principle",
      "After Effects"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Technical Depth",
      "weight": 0.25
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.2
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Certification Alignment",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Soft Skills",
      "weight": 0.1
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    },
    {
      "name": "Growth Potential",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "Dribbble Jobs",
      "url": "https://dribbble.com/jobs"
    },
    {
      "name": "Behance Job List",
      "url": "https://www.behance.net/joblist"
    }
  ],
  "interview_questions": {
    "technical": [
      "Walk me through your design process from research to handoff",
      "How do you approach building a design system?",
      "How do you measure the success of a design change?",
      "Explain your approach to accessibility in design"
    ],
    "behavioral": [
      "Tell me about a time you had to push back on a stakeholder's design request",
      "How do you handle conflicting feedback from multiple stakeholders?",
      "Describe a project where user research changed the direction significantly"
    ],
    "case": [
      "Our checkout flow has a 70% drop-off rate. How would you approach redesigning it?"
    ]
  },
  "resume_style": "modern"
},
  "engineering": {
  "name": "Software Engineering",
  "aliases": [
    "software engineer",
    "developer",
    "DevOps",
    "backend",
    "frontend",
    "full stack",
    "SRE",
    "工程师",
    "エンジニア",
    "Entwickler",
    "développeur"
  ],
  "keywords": {
    "hard_skills": [
      "system design",
      "microservices",
      "REST APIs",
      "GraphQL",
      "CI/CD",
      "containerization",
      "cloud architecture",
      "database design",
      "distributed systems",
      "agile development",
      "code review",
      "performance optimization",
      "security best practices",
      "testing strategies"
    ],
    "soft_skills": [
      "technical communication",
      "cross-functional collaboration",
      "mentoring",
      "problem solving",
      "ownership"
    ],
    "certifications": [
      "AWS Certified",
      "Google Cloud Certified",
      "Azure Certified",
      "Kubernetes CKA",
      "Terraform Associate"
    ],
    "tools": [
      "Git",
      "Docker",
      "Kubernetes",
      "AWS",
      "PostgreSQL",
      "Redis",
      "Terraform",
      "GitHub Actions",
      "Datadog"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Technical Depth",
      "weight": 0.25
    },
    {
      "name": "System Design",
      "weight": 0.15
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.15
    },
    {
      "name": "Industry Experience",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Location Match",
      "weight": 0.05
    },
    {
      "name": "Soft Skills",
      "weight": 0.1
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    },
    {
      "name": "Growth Potential",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "StackOverflow Jobs",
      "url": "https://stackoverflow.com/jobs"
    },
    {
      "name": "HackerNews Who's Hiring",
      "url": "https://news.ycombinator.com"
    }
  ],
  "interview_questions": {
    "technical": [
      "Design a URL shortener service",
      "How would you debug a slow API endpoint?",
      "Explain the CAP theorem and its practical implications"
    ],
    "behavioral": [
      "Tell me about a time you had to make a technical trade-off",
      "How do you handle disagreements in code review?",
      "Describe a production incident you resolved"
    ],
    "case": [
      "Our API latency has increased 5x in the last week. Walk me through your investigation"
    ]
  },
  "resume_style": "modern"
},
  "finance": {
  "name": "Finance, Risk & Compliance",
  "aliases": [
    "audit",
    "compliance",
    "financial",
    "risk",
    "risk management",
    "risk assessment",
    "internal control",
    "internal controls",
    "control testing",
    "treasury",
    "FP&A",
    "accounting",
    "GRC",
    "governance",
    "regulatory",
    "regulatory compliance",
    "cybersecurity",
    "infosec",
    "information security",
    "data privacy",
    "data protection",
    "SOX",
    "SOC 2",
    "ISO 27001",
    "NIST",
    "HIPAA",
    "GDPR",
    "PIPL",
    "合规",
    "财务",
    "审计",
    "风险",
    "Finanz",
    "comptabilité",
    "監査"
  ],
  "keywords": {
    "hard_skills": [
      "SOX compliance",
      "IFRS",
      "GAAP",
      "internal audit",
      "external audit",
      "risk assessment",
      "risk management",
      "control testing",
      "control framework",
      "regulatory compliance",
      "regulatory reporting",
      "governance",
      "GRC",
      "financial modeling",
      "FP&A",
      "DCF analysis",
      "budget variance",
      "financial analysis",
      "forecasting",
      "reconciliation",
      "tax compliance",
      "anti-money laundering",
      "data privacy",
      "GDPR",
      "PIPL",
      "HIPAA",
      "NIST",
      "ISO 27001",
      "SOC 2",
      "PCI-DSS",
      "FedRAMP",
      "COBIT",
      "cybersecurity",
      "information security",
      "third-party risk",
      "vendor risk",
      "audit findings",
      "remediation"
    ],
    "soft_skills": [
      "stakeholder management",
      "cross-functional collaboration",
      "attention to detail",
      "analytical thinking",
      "regulatory communication",
      "executive reporting",
      "program management"
    ],
    "certifications": [
      "CPA",
      "ACCA",
      "CIA",
      "CISA",
      "CISM",
      "CISSP",
      "CRISC",
      "CGEIT",
      "FRM",
      "CFA",
      "CMA",
      "PMP"
    ],
    "tools": [
      "SAP",
      "Oracle",
      "Bloomberg",
      "Excel",
      "Power BI",
      "Tableau",
      "Hyperion",
      "BlackLine",
      "Workiva",
      "Archer",
      "ServiceNow",
      "ServiceNow GRC",
      "Xacta",
      "CSAM"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Regulatory Knowledge",
      "weight": 0.2
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Technical Skills Match",
      "weight": 0.2
    },
    {
      "name": "Certification Alignment",
      "weight": 0.15
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Location Match",
      "weight": 0.05
    },
    {
      "name": "Soft Skills",
      "weight": 0.05
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    },
    {
      "name": "Growth Potential",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "eFinancialCareers",
      "url": "https://www.efinancialcareers.com"
    },
    {
      "name": "Robert Half",
      "url": "https://www.roberthalf.com"
    }
  ],
  "interview_questions": {
    "technical": [
      "Walk me through a DCF model",
      "How do you assess internal control weaknesses?",
      "Explain the difference between IFRS and GAAP",
      "What is SOX 404 and how do you ensure compliance?",
      "How do you perform a risk assessment?"
    ],
    "behavioral": [
      "Describe a time you identified a compliance risk",
      "How do you handle tight audit deadlines?",
      "Tell me about a time you had to communicate a complex financial issue to non-finance stakeholders"
    ],
    "case": [
      "Company X has declining margins. Walk me through your analysis",
      "You discover a material misstatement during an audit. What steps do you take?"
    ]
  },
  "resume_style": "conservative"
},
  "healthcare": {
  "name": "Healthcare & Life Sciences",
  "aliases": [
    "healthcare",
    "medical",
    "clinical",
    "pharmaceutical",
    "biotech",
    "hospital",
    "nursing",
    "医疗",
    "医療",
    "Gesundheitswesen",
    "santé"
  ],
  "keywords": {
    "hard_skills": [
      "clinical research",
      "patient care",
      "regulatory affairs",
      "GCP/GMP/GLP",
      "clinical trial management",
      "medical device",
      "pharmacovigilance",
      "health informatics",
      "HIPAA compliance",
      "FDA submissions",
      "electronic health records",
      "quality assurance",
      "evidence-based practice",
      "population health"
    ],
    "soft_skills": [
      "empathy",
      "teamwork",
      "attention to detail",
      "communication",
      "critical thinking",
      "stress management"
    ],
    "certifications": [
      "RN/BSN",
      "MD",
      "PharmD",
      "PMP (Healthcare)",
      "Lean Six Sigma (Healthcare)",
      "CCRP",
      "RAC"
    ],
    "tools": [
      "Epic",
      "Cerner",
      "Medidata",
      "Veeva",
      "REDCap",
      "CTMS",
      "SAP (Pharma)",
      "Tableau (Healthcare)"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Regulatory Knowledge",
      "weight": 0.25
    },
    {
      "name": "Technical Skills Match",
      "weight": 0.2
    },
    {
      "name": "Certification Alignment",
      "weight": 0.15
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.05
    },
    {
      "name": "Soft Skills",
      "weight": 0.05
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "Health eCareers",
      "url": "https://www.healthecareers.com"
    },
    {
      "name": "BioSpace",
      "url": "https://www.biospace.com"
    }
  ],
  "interview_questions": {
    "technical": [
      "Walk me through the phases of a clinical trial",
      "How do you ensure FDA regulatory compliance in your work?",
      "Explain your approach to pharmacovigilance and adverse event reporting",
      "How do you implement quality improvement in a clinical setting?"
    ],
    "behavioral": [
      "Tell me about a time you had to handle a patient safety concern",
      "How do you stay current with evolving healthcare regulations?",
      "Describe a situation where you improved a clinical process"
    ],
    "case": [
      "A clinical trial site has enrollment 40% below target. What's your action plan?"
    ]
  },
  "resume_style": "conservative"
},
  "hr": {
  "name": "Human Resources",
  "aliases": [
    "HR",
    "human resources",
    "talent acquisition",
    "recruiting",
    "people operations",
    "compensation",
    "benefits",
    "人力资源",
    "人事",
    "Personalwesen",
    "ressources humaines",
    "人事部"
  ],
  "keywords": {
    "hard_skills": [
      "talent acquisition",
      "employee relations",
      "performance management",
      "compensation & benefits",
      "HRIS administration",
      "workforce planning",
      "succession planning",
      "organizational development",
      "change management",
      "labor law compliance",
      "onboarding",
      "diversity & inclusion",
      "employee engagement",
      "training & development",
      "payroll administration"
    ],
    "soft_skills": [
      "empathy",
      "conflict resolution",
      "confidentiality",
      "active listening",
      "negotiation",
      "cultural sensitivity"
    ],
    "certifications": [
      "SHRM-CP",
      "SHRM-SCP",
      "PHR",
      "SPHR",
      "CIPD",
      "CHRP"
    ],
    "tools": [
      "Workday",
      "BambooHR",
      "ADP",
      "Greenhouse",
      "Lever",
      "SAP SuccessFactors",
      "LinkedIn Recruiter",
      "Culture Amp"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Technical Skills Match",
      "weight": 0.2
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Certification Alignment",
      "weight": 0.15
    },
    {
      "name": "Regulatory Knowledge",
      "weight": 0.15
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Soft Skills",
      "weight": 0.1
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "SHRM Job Board",
      "url": "https://jobs.shrm.org"
    },
    {
      "name": "HR Jobs",
      "url": "https://www.hrjobs.com"
    }
  ],
  "interview_questions": {
    "technical": [
      "How do you design a compensation structure for a 200-person company?",
      "Walk me through your approach to reducing employee turnover",
      "How do you ensure compliance with local labor laws across multiple regions?"
    ],
    "behavioral": [
      "Tell me about a difficult employee relations case you handled",
      "How do you balance business needs with employee welfare?",
      "Describe a time you led a significant organizational change"
    ],
    "case": [
      "Employee engagement scores dropped 15% this quarter. What's your action plan?"
    ]
  },
  "resume_style": "conservative"
},
  "legal": {
  "name": "Legal & Compliance",
  "aliases": [
    "legal",
    "lawyer",
    "counsel",
    "attorney",
    "paralegal",
    "corporate law",
    "IP",
    "法律",
    "法務",
    "Recht",
    "juridique"
  ],
  "keywords": {
    "hard_skills": [
      "contract drafting",
      "contract review",
      "regulatory compliance",
      "litigation management",
      "due diligence",
      "corporate governance",
      "intellectual property",
      "employment law",
      "data privacy (GDPR/CCPA)",
      "mergers & acquisitions",
      "risk management",
      "dispute resolution",
      "legal research",
      "policy development"
    ],
    "soft_skills": [
      "analytical reasoning",
      "attention to detail",
      "negotiation",
      "written communication",
      "stakeholder management",
      "ethical judgment"
    ],
    "certifications": [
      "Bar Admission",
      "CIPP (Privacy)",
      "CISA",
      "Certified Compliance & Ethics Professional",
      "LLM"
    ],
    "tools": [
      "Westlaw",
      "LexisNexis",
      "DocuSign",
      "ContractPodAi",
      "Relativity",
      "NetDocuments",
      "Clio"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Regulatory Knowledge",
      "weight": 0.25
    },
    {
      "name": "Technical Skills Match",
      "weight": 0.2
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Certification Alignment",
      "weight": 0.15
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Soft Skills",
      "weight": 0.05
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.05
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "LawJobs",
      "url": "https://www.lawjobs.com"
    },
    {
      "name": "Robert Half Legal",
      "url": "https://www.roberthalf.com/legal"
    }
  ],
  "interview_questions": {
    "technical": [
      "How do you approach reviewing a commercial contract for risk?",
      "Walk me through a due diligence process for an acquisition",
      "How do you ensure GDPR compliance across multiple jurisdictions?",
      "Explain how you would handle a potential IP infringement"
    ],
    "behavioral": [
      "Tell me about a time you had to deliver unwelcome legal advice to leadership",
      "How do you prioritize when managing multiple active matters?",
      "Describe a situation where you found a creative legal solution to a business problem"
    ],
    "case": [
      "A key vendor breaches their SLA. Walk me through your response strategy"
    ]
  },
  "resume_style": "conservative"
},
  "marketing": {
  "name": "Marketing & Growth",
  "aliases": [
    "marketing",
    "digital marketing",
    "brand",
    "content marketing",
    "growth",
    "demand generation",
    "市场营销",
    "マーケティング",
    "Marketing",
    "marketing digital"
  ],
  "keywords": {
    "hard_skills": [
      "SEO/SEM",
      "content strategy",
      "demand generation",
      "marketing automation",
      "A/B testing",
      "conversion rate optimization",
      "paid media",
      "social media marketing",
      "email marketing",
      "brand positioning",
      "go-to-market strategy",
      "product marketing",
      "campaign management",
      "market research",
      "marketing analytics"
    ],
    "soft_skills": [
      "creative thinking",
      "storytelling",
      "cross-functional collaboration",
      "data-driven decision making",
      "stakeholder management",
      "project management"
    ],
    "certifications": [
      "Google Ads Certified",
      "Google Analytics Certified",
      "HubSpot Inbound Marketing",
      "Meta Blueprint",
      "Hootsuite Social Marketing"
    ],
    "tools": [
      "Google Analytics",
      "HubSpot",
      "Marketo",
      "Salesforce Marketing Cloud",
      "Semrush",
      "Ahrefs",
      "Figma",
      "Canva",
      "Mailchimp",
      "Google Ads"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Technical Skills Match",
      "weight": 0.2
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Revenue Track Record",
      "weight": 0.15
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.15
    },
    {
      "name": "Certification Alignment",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Soft Skills",
      "weight": 0.05
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    },
    {
      "name": "Growth Potential",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "MarketingHire",
      "url": "https://www.marketinghire.com"
    },
    {
      "name": "Built In",
      "url": "https://builtin.com"
    }
  ],
  "interview_questions": {
    "technical": [
      "How would you build a demand generation funnel from scratch?",
      "Walk me through how you measure marketing ROI",
      "How do you approach SEO for a new product launch?",
      "Explain your process for A/B testing a landing page"
    ],
    "behavioral": [
      "Tell me about a campaign that failed and what you learned",
      "How do you prioritize when you have multiple campaigns running?",
      "Describe a time you had to convince leadership to invest in a new channel"
    ],
    "case": [
      "Our cost per lead has doubled in 6 months. How would you diagnose and fix this?"
    ]
  },
  "resume_style": "modern"
},
  "operations": {
  "name": "Operations & Supply Chain",
  "aliases": [
    "operations",
    "supply chain",
    "procurement",
    "logistics",
    "project management",
    "ops",
    "运营",
    "オペレーション",
    "Betrieb",
    "opérations"
  ],
  "keywords": {
    "hard_skills": [
      "supply chain management",
      "procurement",
      "inventory management",
      "logistics optimization",
      "vendor management",
      "process improvement",
      "lean manufacturing",
      "Six Sigma",
      "demand planning",
      "warehouse management",
      "capacity planning",
      "cost reduction",
      "quality management",
      "ERP implementation"
    ],
    "soft_skills": [
      "problem solving",
      "cross-functional collaboration",
      "negotiation",
      "analytical thinking",
      "project management",
      "decision making"
    ],
    "certifications": [
      "PMP",
      "CSCP (APICS)",
      "CPIM",
      "Lean Six Sigma Green Belt",
      "Lean Six Sigma Black Belt",
      "CPSM"
    ],
    "tools": [
      "SAP",
      "Oracle SCM",
      "Jira",
      "Microsoft Project",
      "Tableau",
      "Power BI",
      "Asana",
      "NetSuite"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Technical Skills Match",
      "weight": 0.25
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Certification Alignment",
      "weight": 0.15
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.15
    },
    {
      "name": "Revenue Track Record",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Soft Skills",
      "weight": 0.05
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "Supply Chain Online",
      "url": "https://www.supplychainonline.com"
    },
    {
      "name": "APICS Career Center",
      "url": "https://careers.ascm.org"
    }
  ],
  "interview_questions": {
    "technical": [
      "How would you reduce lead time in a global supply chain?",
      "Walk me through a Lean Six Sigma improvement project you led",
      "How do you approach vendor selection and evaluation?",
      "Explain your process for demand forecasting"
    ],
    "behavioral": [
      "Tell me about a time you resolved a critical supply chain disruption",
      "How do you handle competing priorities across multiple projects?",
      "Describe a cost reduction initiative you implemented"
    ],
    "case": [
      "Our fulfillment costs have increased 30% year-over-year. How would you investigate and address this?"
    ]
  },
  "resume_style": "conservative"
},
  "sales": {
  "name": "Sales & Business Development",
  "aliases": [
    "sales",
    "business development",
    "account management",
    "revenue",
    "BD",
    "销售",
    "営業",
    "Vertrieb",
    "ventes"
  ],
  "keywords": {
    "hard_skills": [
      "quota attainment",
      "pipeline management",
      "lead generation",
      "account planning",
      "territory management",
      "sales forecasting",
      "contract negotiation",
      "cold calling",
      "consultative selling",
      "solution selling",
      "channel sales",
      "enterprise sales",
      "SaaS sales",
      "revenue growth"
    ],
    "soft_skills": [
      "relationship building",
      "negotiation",
      "persuasion",
      "resilience",
      "time management",
      "active listening"
    ],
    "certifications": [
      "Salesforce Certified",
      "HubSpot Sales Certification",
      "MEDDIC",
      "Sandler Training"
    ],
    "tools": [
      "Salesforce",
      "HubSpot",
      "Outreach",
      "Gong",
      "LinkedIn Sales Navigator",
      "ZoomInfo",
      "Clari"
    ]
  },
  "scoring_dimensions": [
    {
      "name": "Revenue Track Record",
      "weight": 0.25
    },
    {
      "name": "Industry Experience",
      "weight": 0.15
    },
    {
      "name": "Sales Methodology",
      "weight": 0.15
    },
    {
      "name": "Tool Proficiency",
      "weight": 0.1
    },
    {
      "name": "Seniority Fit",
      "weight": 0.1
    },
    {
      "name": "Location Match",
      "weight": 0.05
    },
    {
      "name": "Soft Skills",
      "weight": 0.1
    },
    {
      "name": "Company Culture Fit",
      "weight": 0.05
    },
    {
      "name": "Growth Potential",
      "weight": 0.05
    }
  ],
  "job_portals": [
    {
      "name": "RepVue",
      "url": "https://www.repvue.com"
    },
    {
      "name": "Bravado",
      "url": "https://www.bravado.co"
    }
  ],
  "interview_questions": {
    "technical": [
      "Walk me through your sales process from prospecting to close",
      "How do you qualify a lead using MEDDIC or BANT?",
      "Describe how you manage a complex enterprise deal cycle"
    ],
    "behavioral": [
      "Tell me about a deal you lost and what you learned",
      "How do you handle a prospect who goes silent?",
      "Describe a time you exceeded your quota significantly"
    ],
    "case": [
      "You inherit a territory with zero pipeline. What do you do in the first 90 days?"
    ]
  },
  "resume_style": "executive"
},
};
